export const GYMS = [
    {
      id: '1',
      name: 'FitZone Elite',
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80',
      location: 'Downtown',
      basePrice: 100,
      trainerPrice: 80,
      rating: 4.8,
      openHours: '6:00 AM - 10:00 PM',
      description: 'State-of-the-art fitness facility with expert trainers and modern equipment.',
      trainers: [
        { id: '1', name: 'John Smith', specialization: 'Strength Training', price: 50 },
        { id: '2', name: 'Sarah Johnson', specialization: 'HIIT', price: 45 },
        { id: '3', name: 'Mike Wilson', specialization: 'CrossFit', price: 55 },
      ],
    },
    {
      id: '2',
      name: 'PowerHouse Gym',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80',
      location: 'Westside',
      basePrice: 120,
      trainerPrice: 100,
      rating: 4.6,
      openHours: '5:00 AM - 11:00 PM',
      description: 'High-end gym with advanced machines and personal training programs.',
      trainers: [
        { id: '1', name: 'Alex Taylor', specialization: 'Bodybuilding', price: 60 },
        { id: '2', name: 'Raju Singh', specialization: 'Bodybuilding', price: 120 },
        { id: '3', name: 'Emma Wilson', specialization: 'Yoga', price: 40 },
      ],
    },
    {
      id: '3',
      name: 'CrossFit Central',
      image: 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80',
      location: 'Midtown',
      basePrice: 140,
      trainerPrice: 80,
      rating: 4.9,
      openHours: '6:00 AM - 9:00 PM',
      description: 'High-end gym with advanced machines and personal training programs.',
      trainers: [
        { id: '1', name: 'Alex Taylor', specialization: 'Bodybuilding', price: 60 },
        { id: '2', name: 'Emma Wilson', specialization: 'Yoga', price: 40 },
        { id: '3', name: 'Buudy Wsing', specialization: 'Yoga', price: 20 },
        { id: '4', name: 'Anshul Jain', specialization: 'Yoga', price: 30 },
        { id: '5', name: 'Shubh Jain', specialization: 'Yoga', price: 70 },
        { id: '6', name: 'Jayufg Dfyea', specialization: 'Yoga', price: 90 },
      ],
    },
  ];
  